
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5

production:
  adapter:  mysql2
  host:     <%= ENV.fetch('DB_HOST') %>
  database: <%= ENV.fetch('DB_NAME') %>
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASS') %>

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 8
